<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Chronicle.Plugin.LastFM</AssemblyName>
    <RootNamespace>Chronicle.Plugin.LastFM</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Chronicle/src/Chronicle.Plugins/Chronicle.Plugins.csproj" />
  </ItemGroup>
</Project>